package com.jmpp.server;

import java.util.Set;

import javax.websocket.Session;

public class JMPPSession {
	
	/** 
	 * Session generated from WebSocket Endpoint
	 */
	Session session;
	
	/**
	 * Display name as provided by the user
	 */
	String displayName;
	
	/**
	 * Identifier as generated by the client
	 */
	String identifier;
	
	public JMPPSession(Session session)
	{
		this.session = session;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Session getSession() {
		return this.session;
	}
	
	public static JMPPSession getJMPPSessionBySession(Set<JMPPSession> userSessions, Session session)
    {
    	 for (JMPPSession jmppSession : userSessions) 
	     {
    		 if(jmppSession.getSession().equals(session))
    			 return jmppSession;
	     }
    	
    	return null;
    }
    
	public static JMPPSession getJMPPSessionByIdentifier(Set<JMPPSession> userSessions, String identifier)
    {
    	 for (JMPPSession jmppSession : userSessions) 
	     {
    		 if(jmppSession.getIdentifier() != null && jmppSession.getIdentifier().equals(identifier))
    			 return jmppSession;
	     }
    	
    	return null;
    }
    
	public static JMPPSession getJMPPSessionByDisplayName(Set<JMPPSession> userSessions, String displayName)
    {
    	 for (JMPPSession jmppSession : userSessions) 
	     {
    		 if(jmppSession.getDisplayName() != null && jmppSession.getDisplayName().equals(displayName))
    			 return jmppSession;
	     }
    	
    	return null;
    }
}
